### ISSUE TITLE
Fail to initialize on Mac OS

### ISSUE THREAD

**Issue by vijghph** [buttonfreak/goodwe-api#7]
I am getting an error message on mac when running "npm link"

ACCES: permission denied, symlink '/Users/xxxxx/dev/goodwe-api-master' -> '/usr/local/lib/node_modules/goodwe-api'

**Comment by vijghph** [comment]
I found a way to address this:
https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md

**Comment by vijghph** [comment]
....but now getting another error when running it:

`The "path" argument must be of type string. Received type object TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:1088:7)
    at new Persistent (/Users/philippe/dev/goodwe-api-master/dist/lib/classes/Persistent.js:40:58)
    at _callee$ (/Users/philippe/dev/goodwe-api-master/dist/lib/classes/GoodWeFetch.js:42:18)
    at tryCatch (/Users/philippe/dev/goodwe-api-master/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/philippe/dev/goodwe-api-master/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/philippe/dev/goodwe-api-master/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Users/philippe/dev/goodwe-api-master/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/philippe/dev/goodwe-api-master/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /Users/philippe/dev/goodwe-api-master/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7

**Comment by buttonfreak** [comment]
Hi,

I've tried to reproduce the issue, unfortunately without the errors you had. Looks to me like the link script isn't able to write to the required folders.

**Comment by vijghph** [comment]
Non-issue, indeed.

- I had to install manually a number of dependant packages (eslint, eslint-plugin-react)
- and to ensure the environment variable had been exported in my bash script. Sorry to have failed to remember that (as I didn't write scripts for 12+ years)

Now it works.
